name = "%VENDOR_NAME%/%PROJECT_NAME%"
version = "0.0.0"
compiler = "%AIKEN_VERSION%"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project '%VENDOR_NAME%/%PROJECT_NAME%'"

[repository]
user = "%VENDOR_NAME%"
project = "%PROJECT_NAME%"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "%STDLIB_VERSION%"
source = "github"

[config]
